import { getDialect } from '../parser/dialects';
import type { DatabaseSchema, SqlDialect } from '../parser/types';
import { FIELD_CASING_OPTIONS } from './casingUtils';
import { buildGenerationModel, type GenerationModel } from './model';
import { OUTPUT_MODE_OPTIONS, type GeneratorOptions } from './options';
import { generateTypeScript } from './typescriptGenerator';
import { generateZod } from './zodGenerator';

export interface GeneratedOutput {
  code: string;
  model: GenerationModel;
}

function header(model: GenerationModel): string[] {
  const { options } = model;
  const tableCount = model.tables.length;
  const mode = OUTPUT_MODE_OPTIONS.find((o) => o.id === options.outputMode)?.label ?? options.outputMode;
  const casing = FIELD_CASING_OPTIONS.find((o) => o.id === options.fieldCasing)?.label ?? options.fieldCasing;
  return [
    '// Generated by SQL DDL to TypeScript & Zod Schema Generator (HiMat Tech)',
    `// Source dialect: ${getDialect(model.dialect).label} · ${tableCount} ${tableCount === 1 ? 'table' : 'tables'} · ${mode} · ${casing} fields`,
  ];
}

/** Converts a parsed schema into the final source file for the selected output mode. */
export function generateCode(schema: DatabaseSchema, dialect: SqlDialect, options: GeneratorOptions): GeneratedOutput {
  const model = buildGenerationModel(schema, dialect, options);
  if (model.tables.length === 0 && model.enums.length === 0) return { code: '', model };

  const sections: string[] = [header(model).join('\n')];

  switch (options.outputMode) {
    case 'ts':
      sections.push(...generateTypeScript(model));
      break;
    case 'zod':
      sections.push('import { z } from "zod";', ...generateZod(model, { includeTypes: false }));
      break;
    case 'ts-zod':
      sections.push('import { z } from "zod";', ...generateZod(model, { includeTypes: true }));
      break;
  }

  return { code: `${sections.join('\n\n')}\n`, model };
}
